### ISSUE TITLE
A congrat notice

### ISSUE THREAD

**Issue by nodgear** [sylv/micro#4]
This is one of the best projects i saw this week.
why? Because the other projects with same scope have either too many features or are too bare bones.

But now to the issue: readme says it's not important now, but having deploy instructions would make it easier for collaborators join your project, making it progress faster.

**Comment by sylv** [comment]
Pretty sure anyone that could contribute would know how to set it up in the first place, it's pretty standard. There aren't instructions on how to set it up yet because there are things that can't be customised such as the home page that some people might want to change. There is a half complete future update that should address that and other issues though.
